# Generated by Django 2.2.4 on 2021-02-14 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OCR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='ocr/')),
                ('owner', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('email', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('pw', models.CharField(max_length=60)),
                ('height', models.FloatField(null=True)),
                ('age', models.IntegerField(null=True)),
                ('sex', models.BooleanField(null=True)),
                ('aka', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Change',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(default=0)),
                ('muscle', models.FloatField(default=0)),
                ('fat', models.FloatField(default=0)),
                ('water', models.FloatField(default=0)),
                ('protein', models.FloatField(default=0)),
                ('mineral', models.FloatField(default=0)),
                ('date', models.DateField()),
                ('score', models.IntegerField(default=0)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.User')),
            ],
        ),
    ]
