# Generated by Django 2.2.4 on 2021-01-16 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pw',
            field=models.CharField(max_length=256),
        ),
    ]
