# Generated by Django 2.2.4 on 2021-01-16 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210116_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pw',
            field=models.CharField(max_length=60),
        ),
    ]
