# Generated by Django 2.2.4 on 2021-03-08 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='picture',
            old_name='Thigh',
            new_name='thigh',
        ),
    ]
