# Generated by Django 2.2.4 on 2021-03-28 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210308_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='picture',
            field=models.ImageField(null=True, upload_to='body_profile/'),
        ),
    ]
