# Generated by Django 2.2.4 on 2021-02-11 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_ocr'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocr',
            name='owner',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
