# Generated by Django 2.2.4 on 2021-04-05 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_picture_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='army',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='target',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
