# Generated by Django 2.2.4 on 2021-02-11 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_ocr_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='aka',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='height',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.BooleanField(null=True),
        ),
        migrations.CreateModel(
            name='change',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(null=True)),
                ('muscle', models.FloatField(null=True)),
                ('fat', models.FloatField(null=True)),
                ('water', models.FloatField(null=True)),
                ('protein', models.FloatField(null=True)),
                ('date', models.DateField(null=True)),
                ('score', models.IntegerField(null=True)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.User')),
            ],
        ),
    ]
