# Generated by Django 2.2.4 on 2021-04-11 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210405_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='target',
            field=models.CharField(default=0, max_length=1, null=True),
        ),
    ]
