# Generated by Django 2.2.4 on 2021-02-12 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_change_mineral'),
    ]

    operations = [
        migrations.RenameField(
            model_name='change',
            old_name='Mineral',
            new_name='mineral',
        ),
    ]
