# Generated by Django 2.2.4 on 2021-04-17 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210411_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='num',
            field=models.SmallIntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='user',
            name='part',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='way',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='army',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='target',
            field=models.CharField(default=0, max_length=1),
        ),
    ]
